import type { Metadata } from "next";
import {Inter,Poppins} from "next/font/google";
import Header from "@/components/Header/Header"
import Footer from "@/components/Footer/Footer"
import "./globals.css";

const inter=Inter({subsets:['latin'],
  variable:"--inter"
})

const poppins = Poppins({ 
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  variable: "--poppins" 
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.variable}
      >
        <Header></Header>

        {children}
        <Footer></Footer>

      </body>
    </html>
  );
}
